stages:
  - test

api-tests:
  stage: test
  image: node:18-alpine
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: testdb
    POSTGRES_USER: testuser
    POSTGRES_PASSWORD: testpass
    DATABASE_URL: "postgresql://testuser:testpass@postgres:5432/testdb"
    JWT_SECRET: "test-secret-key-for-ci"
  script:
    - apk add --no-cache python3 py3-pip
    - pip3 install -r requirements.txt --break-system-packages
    - npm install -g newman
    - python3 -c "from app.database import engine, Base; Base.metadata.create_all(bind=engine)"
    - python3 app/seed/mock_data.py
    - python3 -m uvicorn app.main:app --host 127.0.0.1 --port 8000 &
    - sleep 10
    - newman run SteamAPI.postman_collection.json --environment localhost.postman_environment.json
