"""add background, recommendations, movies, screenshots

Revision ID: 7c1e4aacec2b
Revises: 
Create Date: 2026-06-05 20:00:53.141794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c1e4aacec2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('background', sa.String(), nullable=True))
    op.add_column('games', sa.Column('recommendations', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('movies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('screenshots', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sync_state', sa.Column('gap_sync_checkpoint', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_state', 'gap_sync_checkpoint')
    op.drop_column('games', 'screenshots')
    op.drop_column('games', 'movies')
    op.drop_column('games', 'recommendations')
    op.drop_column('games', 'background')
    # ### end Alembic commands ###
